model: ContrastiveEmbeddingModel
run_config :
  verbose : 2
  debug : True
  num_threads : 64

model_config :
  name : ContrastiveModel
  projection_dim : 8
  projection_blocks : 4
  backbone_layers : [64,256]
  latent_dim : 2
  encoder_layers : [64,32]
  decoder_layers : [32,64]

training_config :
  constrastive_epochs : 2
  epochs : 20
  batch_size : 5642
  emb_learning_rate : 0.001
  emb_learning_rate_decay : 0.000001
  learning_rate : 0.001
  validation_split : 0.1
  

  EarlyStopping_patience : 10

  ReduceLROnPlateau_factor : 0.5
  ReduceLROnPlateau_patience : 5
  ReduceLROnPlateau_min_lr : 0.00001

  embedding_loss : 'SupSimCLR'
  #embedding_loss : 'VICReg'