model: EmbeddingQECPLModel
run_config :
  verbose : 2
  debug : True
  num_threads : 64

model_config :
  name : q
  latent_dim : 1
  embedding_dim : 8
  n_layers : 3

training_config :
  epochs : 70
  batch_size : 1000
  learning_rate : 0.2
