model: PennyLaneQAEModel
run_config :
  verbose : 2
  debug : True
  num_threads : 64

model_config :
  name : qae
  latent_dim : 1

training_config :
  epochs : 100
  batch_size : 10
  learning_rate : 0.2
