model: TransformerContrastiveEmbeddingModel
run_config :
  verbose : 2
  debug : True
  num_threads : 64

model_config :
  name : TransformerContrastiveModel
  projection_dim : 8
  projection_blocks : 3
  num_heads : 4
  num_layers : 2
  ff_dim : 64
  embed_dim : 32
  dropout_rate : 0.1
  backbone_layers : [32,16]
  latent_dim : 4
  encoder_layers : [8,6]
  decoder_layers : [6,8]
  num_jets : 10
  num_muons : 4
  num_electrons : 4
  use_positional_embeddings : True

training_config :
  contrastive_epochs : 10
  epochs : 20
  batch_size : 64
  emb_learning_rate : 0.0001
  learning_rate : 0.0001
  validation_split : 0.1
  emb_learning_rate_decay : 0.000001

  EarlyStopping_patience : 10

  ReduceLROnPlateau_factor : 0.5
  ReduceLROnPlateau_patience : 5
  ReduceLROnPlateau_min_lr : 0.00001

  embedding_loss : 'SimCLR'
  #embedding_loss : 'VICReg'
  #embedding_loss : 'SupSimCLR'
